const adminRegistration = require('./registration.js')
const adminLogin=require('./login.js')
const departmentOperations=require('./departments/department.js')
const staffOperation=require('./staff/staff.js')
const patient = require('./patient/patient.js')
const treatment = require('./treatment/treatment.js')
const invoice = require('./invoice/invoice.js')